# Use the official .NET SDK image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./SnapNBuyBackend.csproj"
RUN dotnet build "./SnapNBuyBackend.csproj" -c Release -o /app/build
RUN dotnet publish "./SnapNBuyBackend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SnapNBuyBackend.dll"]
